---
# 本地socks5绑定地址
host: 0.0.0.0:12333
# 缓冲队列容量
buff_size: 1000
# 服务端地址 (多个)
remote:
  # 名称
  - name: local
    # 协议
    proctol: tcp
    # 连接数
    connections: 1
    # ip 地址
    host: 127.0.0.1:12345
    # 密钥
    key: "123a"
  - name: local2
    protocol: quic
    server_name: test
    host: 127.0.0.1:12346
    cert: d://test.der
