---
# 本地socks5绑定地址
host: 0.0.0.0:12333
# 服务端地址 (多个)
remote:
  # 名称
  - name: local
    # 缓冲队列容量
    buffSize: 1000
    # 协议
    protocol: tcp
    # 连接数
    connections: 1
    # ip 地址
    host: 127.0.0.1:12345
    # 密钥
    key: "123a"
