---
# socks5 监听地址
socks5Listen: 0.0.0.0:12333
# http/https 监听地址
httpListen: 0.0.0.0:10800
# 协议
protocol: tcpmux
# 缓冲池容量
buffSize: 2048
# 缓冲队列容量
channelCapacity: 500

# 服务端地址 (多个)
remote:
  # 名称
  - name: local
    # 连接数
    connections: 3
    # 地址
    host: 127.0.0.1:12345
    # 证书路径
    certPath: ""
    # server name
    serverName: "proxy"
